### ISSUE TITLE
No barronbooks directory

### ISSUE THREAD

**Issue by dojoteef** [salesforce/booksum#10]
The pinkmonkey script outputs summaries into [a pinkmonkey directory](https://github.com/salesforce/booksum/blob/main/scripts/data_collection/pinkmonkey/get_summaries.py#L23), but [summary_chapter_matched_intermediate.jsonl](https://github.com/salesforce/booksum/blob/main/alignments/summary_chapter_matched_intermediate.jsonl) and the jsonl files in [chapter-level-summary-alignments](https://github.com/salesforce/booksum/tree/main/alignments/chapter-level-summary-alignments) seem to expect a barronbooks directory instead.

Additionally, the [basic_clean.py](https://github.com/salesforce/booksum/blob/main/scripts/data_cleaning/basic_clean.py) and [clean_summaries.py](https://github.com/salesforce/booksum/blob/main/scripts/data_cleaning/clean_summaries.py) scripts, seem to expect barronbooks as well. Maybe, the pinkmonkey script should output into a barronbooks directory instead?

**Comment by jigsaw2212** [comment]
The directory name has already been fixed.

**Comment by dojoteef** [comment]
Thanks for taking a look! Unfortunately, I think the fix you applied doesn't work.

It seems that your fix was to change `'barronbooks'` to `'pinkmonkey'` in [basic_clean.py](https://github.com/salesforce/booksum/blob/main/scripts/data_cleaning/basic_clean.py#L18) and [clean_summaries.py](https://github.com/salesforce/booksum/blob/main/scripts/data_cleaning/clean_summaries.py). That conflicts with the 'jsonl' alignments files (so a bug still exists).

I would suggest reverting basic_clean.py and clean_summaries.py. Instead, I think the minimal fix would be to change the output directory of the [pinkmonkey script](https://github.com/salesforce/booksum/blob/main/scripts/data_collection/pinkmonkey/get_summaries.py#L23) to be barronbooks.
