### ISSUE TITLE
Absolute path in book and chapter alignments

### ISSUE THREAD

**Issue by dojoteef** [salesforce/booksum#12]
The jsonl files in [chapter-level-summary-alignments](https://github.com/salesforce/booksum/tree/main/alignments/chapter-level-summary-alignments) and [book-level-summary-alignments](https://github.com/salesforce/booksum/tree/main/alignments/book-level-summary-alignments) use an absolute path for `book_path`, `chapter_path`, and `summary_path` which begins with `/export/longsum/booksumm/`, e.g.

```
{
  ...
  "book_path": "/export/longsum/booksumm/all_chapterized_books/1023-chapters/63.txt",
  "summary_path": "/export/longsum/booksumm/all_chapterized_books/4517-chapters/book_clean.txt",
  ...
}
```

or

```
{
  ...
  "chapter_path": "/export/longsum/booksumm/all_chapterized_books/1023-chapters/63.txt",
  "summary_path": "/export/longsum/booksumm/finished_summaries/gradesaver/Bleak House/section_18_part_2.txt",
  ...
}
```

For the chapter-level summaries, this causes the [gather_data.py](https://github.com/salesforce/booksum/blob/main/alignments/paragraph-level-summary-alignments/gather_data.py) script to fail at these two lines: [gather.py:179](https://github.com/salesforce/booksum/blob/main/alignments/paragraph-level-summary-alignments/gather_data.py#L179) and [gather.py:189](https://github.com/salesforce/booksum/blob/main/alignments/paragraph-level-summary-alignments/gather_data.py#L189). I'm not sure where the book-level summaries are used.

**Comment by jigsaw2212** [comment]
@dojoteef I resolved this issue in the latest commit. The use case for book-level summaries has been specified in #13.
