### ISSUE TITLE
Unnecessary in align_data_bi_encoder_paraphrase.py

### ISSUE THREAD

**Issue by dojoteef** [salesforce/booksum#14]
There are a few unnecessary imports in aligh_data_bi_encoder_paraphrase.py which should be removed:
1. `import rouge`
2. `import rouge.rouge_score as rouge_score`
3. `from nltk.stem.snowball import SnowballStemmer`
4. `from nltk.translate.meteor_score import meteor_score`
5. `from bert_score import BERTScorer`
6. `from transformers import AutoTokenizer`
7. `from nltk.tokenize import word_tokenize, sent_tokenize`

Some like the rouge and bert_score packages are not used at all and require users to install the package to run the script, even though they will never be used.

**Comment by jigsaw2212** [comment]
Unnecessary imports have been cleaned up. Thanks for brining it to our attention!
