### ISSUE TITLE
GPU error running align_data_bi_encoder_paraphrase.py

### ISSUE THREAD

**Issue by dojoteef** [salesforce/booksum#15]
When running on GPU, [align_data_bi_encoder_paraphrase.py:157](https://github.com/salesforce/booksum/blob/f94c7fbdb361478e7957466f7c0db20137ecd92e/alignments/paragraph-level-summary-alignments/align_data_bi_encoder_paraphrase.py#L157) throws an error because the cuda tensor cannot be directly converted to a numpy array. Adding a `.cpu()` before the `.numpy()` seems to fix it for me.

**Comment by jigsaw2212** [comment]
Issue fixed in the latest commit.
