### ISSUE TITLE
Wrong File Open Mode in <align_data_bi_encoder_paraphrase.py>

### ISSUE THREAD

**Issue by moutaigua8183** [salesforce/booksum#18]
In `align_data_bi_encoder_paraphrase.py` at **line 226**,  the file is opened with `write` mode. It seems a bug to me as it is supposed to the `append` mode.   I spent 3 hours only to find that the output file kept being overwritten by the new samples.
```python
# Original 
with open(basename(args.data_path) + ".stable.bi_encoder_paraphrase", "w") as fd:  
    for stable_example in stable_examples:  
        fd.write(json.dumps(stable_example) + "\n")  
# expected
with open(basename(args.data_path) + ".stable.bi_encoder_paraphrase", "a") as fd:  
    for stable_example in stable_examples:  
        fd.write(json.dumps(stable_example) + "\n")  
```

Also a kind suggestion for the usage of `tqdm`:    at **line 197**,  probably `enumerate(tqdm(data))` is preferred.
```python
# original
for ix, example in tqdm(enumerate(data)):
# preferred
for ix, example in enumerate(tqdm(data)):
```

**Comment by jigsaw2212** [comment]
Hi @moutaigua8183,
The issue has been fixed in the latest commit.
