### ISSUE TITLE
Pages are not available

### ISSUE THREAD

**Issue by vamsibanda** [salesforce/booksum#2]
Most of the chapter summary pages are unavailable on the web archive. Do you have the same issue?

Example - 
https://web.archive.org/web/20200924201957/https://www.gradesaver.com/stamped-racism-antiracism-and-you/study-guide/summary-section-v-1963-today

**Comment by jigsaw2212** [comment]
@vamsibanda  Unfortunately, the web archive servers are not always reliable when it comes to collecting the summary data. You could try running the same scripts with some other web archived version of gradesaver and see if that helps?
