### ISSUE TITLE
NotADirectoryError[WinError 267]

### ISSUE THREAD

**Issue by SpaceTime1999** [salesforce/booksum#21]
Hello, When I tried to get the summary of "46. Narrative of the Life of Frederick Douglass: An American Slave", a NotADirectoryError[WinError 267] raised. 

The referenced directory is like
'../../raw_summaries/cliffnotes/summaries\\Narrative of the Life of Frederick Douglass: An American Slave'

(It is easy to modify the tsv.pruned file to solve it.)

**Comment by jigsaw2212** [comment]
Hi @SpaceTime1999. I am unable to recreate this error with  "46. Narrative of the Life of Frederick Douglass: An American Slave", when collecting the summaries. What step are you exactly facing this issue on?

**Comment by Sotwi** [comment]
@jigsaw2212 I faced similar problems when running `python get_summaries.py`
It has to do with Windows' inability to handle colons in file and directory names. You wouldn't be able to replicate the error on a unix system.

As @SpaceTime1999 points out, removing the colons from the books' names in `literature_links.tsv.pruned` is enough to solve the "issue".

**Comment by jigsaw2212** [comment]
@Sotwi-zz thanks so much for pointing out that the issue is Windows specific. We will update the README with this troubleshooting tip!
