### ISSUE TITLE
Which scripts used to fine-tune t5 model after final alignment .jsonl files generated?

### ISSUE THREAD

**Issue by GenTxt** [salesforce/booksum#24]
Have generated all final alignment files and have tested several t5 fine-tuning scripts with different degrees of success.

Seeking to reproduce results from:

Table 8: Examples of decoded summaries of the Chapter 1 of “Sense and Sensibility”, part 2.

Table 11: Examples of decoded summaries of the full text of “Sense and Sensibility”, part 3.

Could you please provide information on scripts and parameters used to generate the above results.

Have tested latest version of transformers  'run_summarization.py' but it yields the following error on the .jsonl

TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]

Have tested other scripts using the "summarize :" option with same .jsonl. These work but only generate a single line summary for Chapter 1 above. How was the multi-line summary for Chapter 1 and the entire book generated?

Looking forward to your reply.

**Comment by jigsaw2212** [comment]
Hi @GenTxt. If you look closely at the experiment setup in section 4.2 of the paper, we follow a generate and rank approach, where we generate summaries for the paragraphs at the book and chapter level, and then rank them to get the top-_k_ summary sentences. The value of _k_ is chosen based on summary length statistics in the training set.
