### ISSUE TITLE
Numbers of Books

### ISSUE THREAD

**Issue by geeraay** [salesforce/booksum#3]
Hi, @jigsaw2212 and @muggin 

Thanks for sharing the scripts for reproducing the BookSum dataset.
I'm still running the `get_works.py` and `get_summaries.py` as it took some time to complete.

I have a few things to confirm:

1. Meanwhile I read on your paper it says that the BookSum Full contains 436 documents, but in the Gutenberg project Zipped file, it contains only 269 folders (I assume it is corresponding with the number of books). Can you explain the count mismatch?

2. Could you explain the relationship among numbers of paragraphs, chapters, and books? Do all the paragraphs belong to chapters, and the chapters belong to books?

Cheers

**Comment by geeraay** [comment]
I think I understand now by reading the alignments *.jsonl files.

**Comment by jigsaw2212** [comment]
@geeraay we have multiple book summaries from different sources, for the same book. And you're right about the relationship between the paragraphs, chapters and books.
