### ISSUE TITLE
README Issues

### ISSUE THREAD

**Issue by dojoteef** [salesforce/booksum#4]
I've run into a few issue with the README:

1. In Steps 2 and 3 of the Usage section, the python scripts must be called from the individual directories, rather than specifying the full script path from the base of the repo. That's because the scripts use hardcoded relative paths
2. The gather_data.py script under Data Alignments requires a number of parameters to be passed in. It's not entirely clear which are the correct parameters (for example, `--join_strings` and `--split_paragraphs` are two mutually exclusive flags and one must be specified). A similar issue exists with the other two alignment scripts (e.g. `--stable_alignment` vs `--greedy_alignment` for align_data_bi_encoder_paraphrase.py). It would be useful to have an example of the exact arguments need for each of these scripts.
3. It would also be quite useful to know what the python package requirements are. While it's possible to look at the scripts manually to see which packages were used, it's hard to determine what versions of the packages are needed. Either documenting this in the README, or including a requirements.txt with pinned versions would be useful.

**Comment by jigsaw2212** [comment]
The README has been updated for 1 and 2. Thanks for pointing these out @dojoteef. We shall add a requirements.txt with pinned versions soon.

**Comment by dojoteef** [comment]
Thanks for updating the README!

It looks like you didn't fully address issue #&#x2060;2 though. Those scripts I highlighted also take a path. What path are they looking for? Can you give an example invocation, e.g.:

```
python paragraph-level-summary-alignments/gather_data.py --split_paragraphs --matched_file <some_path>
```

What should be filled in for `<some_path>` above? The same issue exists for each script in [paragraph-level-summary-alignments](https://github.com/salesforce/booksum/tree/main/alignments/paragraph-level-summary-alignments).
