### ISSUE TITLE
Crash bugs in split_aggregate_chaps_all_sources.py

### ISSUE THREAD

**Issue by dojoteef** [salesforce/booksum#5]
There are couple of crash issues in this script:

1. The summary_path in the jsonl scripts [do not prepend](https://github.com/salesforce/booksum/blob/main/scripts/data_cleaning/split_aggregate_chaps_all_sources.py#L395) a relative link to the parent directory, but the basic_clean.py script outputs them in the [parent directory](https://github.com/salesforce/booksum/blob/main/scripts/data_cleaning/basic_clean.py#L27). This causes the script to crash.
2. [Line 397](https://github.com/salesforce/booksum/blob/main/scripts/data_cleaning/split_aggregate_chaps_all_sources.py#L397) assumes the summary path exists, but it might not, see [line 409](https://github.com/salesforce/booksum/blob/main/scripts/data_cleaning/split_aggregate_chaps_all_sources.py#L409). The try/except block should probably get moved before line 397.

**Comment by jigsaw2212** [comment]
Issue 1 has been fixed, it was due to a slight change of path in the intermediate alignments file. Issue 2 should not occur generally if all the data has been successfully collected from web archive, however, I have added extra checks for the summary path. Thanks @dojoteef!
