### ISSUE TITLE
Crash bug in sparknotes/get_works.py

### ISSUE THREAD

**Issue by dojoteef** [salesforce/booksum#8]
On [line 33](https://github.com/salesforce/booksum/blob/main/scripts/data_collection/sparknotes/get_works.py#L33), the `continue` should instead return `scraped_links` (or equivalently an empty list), since the `continue` is not inside a loop.

**Comment by jigsaw2212** [comment]
Fixed. Although, since we collect all the links from the index page directly, this issue shouldn't be crashing the script.
