### ISSUE TITLE
Data cleaning scripts error handling

### ISSUE THREAD

**Issue by dojoteef** [salesforce/booksum#9]
I'm not sure if this is needed once the remaining issues get ironed out for the dataset scripts as a whole, but right now both the basic_clean.py and clean_summaries.py scripts can crash out if a book directory isn't found. You want to add a `continue` if the `books_dir` is not found at [basic_clean.py:29](https://github.com/salesforce/booksum/blob/main/scripts/data_cleaning/basic_clean.py#L29) or if `source_summary_dir` isn't found at [clean_summaries.py:32](https://github.com/salesforce/booksum/blob/main/scripts/data_cleaning/clean_summaries.py#L32).

**Comment by jigsaw2212** [comment]
One should not run into this issue generally, because you only clean a particular source once the data for it has been collected.
